apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leave-system
  template:
    metadata:
      labels:
        app: leave-system
    spec:           # This line must align with metadata above
      containers:
      - name: leave-container
        image: harishr7/leave-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
