apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-app  # <--- This must match your rollout command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leave-system
  template:
    metadata:
      labels:
        app: leave-system
     spec:
      containers:
      - name: leave-container
        image: harishr7/leave-app:latest
        imagePullPolicy: IfNotPresent  # <--- Add this line

        ports:
        - containerPort: 8080
